services:
  lithium-api:
    build:
      context: .
      dockerfile: ./lithium.dockerfile
    env_file:
      - path: ./.env
    volumes:
      - ./app:/app
      - ./torrc:/etc/tor/torrc
    ports:
      - 4108:4108
    container_name: lithium-api
    command: /bin/sh -c "tor -f /etc/tor/torrc & uvicorn app.main:lithium --ssl-keyfile /app/key.pem --ssl-certfile /app/cert.pem --workers 4 --host 0.0.0.0 --port 8000"
    depends_on:
      - lithium-db
    restart: always
    deploy:
      resources:
        limits:
          memory: 2G

  lithium-db:
    image: postgres:13.0-alpine
    volumes:
      - ./postgres:/var/lib/postgresql/data/
    env_file:
      - path: ./.env
    restart: always
    container_name: lithium-db
    deploy:
      resources:
        limits:
          memory: 128M
